<?php
/**
 * Yandex Autocomplete
 * 
 * @author Slava Yurthev
 */
?>
<?php $helper = Mage::helper('sy_yandex_autocomplete'); ?>
<script type="text/javascript">
	<?php if($helper->getStoreConfig('active') == "1"): ?>
		sy.yandex.autocomplete.config.sender_id = "<?php echo $helper->getStoreConfig('sender_id'); ?>";
		sy.yandex.autocomplete.config.client_id = "<?php echo $helper->getStoreConfig('client_id'); ?>";
	<?php endif; ?>
</script>